name: build_x86_64_tag

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          tags: |
            ghcr.io/isalikov/goservice/x86_64:${{ steps.vars.outputs.tag }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
